In [ ]:
import sys

# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("Hello, World!")
    print(f"Python version: {sys.version}")
else:
    print("Please use Python 3.6 or higher.")



Hello, World!
Python version: 3.13.2 (tags/v3.13.2:4f8bb39, Feb  4 2025, 15:23:48) [MSC v.1942 64 bit (AMD64)]


In [ ]:
4.1 Exercise on Functions:
Task - 1:


In [ ]:
def length_conversion(value, from_unit, to_unit):
    length_units = {
        "meters": 1,
        "kilometers": 0.001,
        "centimeters": 100,
        "millimeters": 1000,
        "miles": 0.000621371,
        "yards": 1.09361,
        "feet": 3.28084,
        "inches": 39.3701
    }
    
    if from_unit not in length_units or to_unit not in length_units:
        return None
    return value * (length_units[to_unit] / length_units[from_unit])

def weight_conversion(value, from_unit, to_unit):
    weight_units = {
        "grams": 1,
        "kilograms": 0.001,
        "milligrams": 1000,
        "pounds": 0.00220462,
        "ounces": 0.035274
    }
    
    if from_unit not in weight_units or to_unit not in weight_units:
        return None
    return value * (weight_units[to_unit] / weight_units[from_unit])

def volume_conversion(value, from_unit, to_unit):
    volume_units = {
        "liters": 1,
        "milliliters": 1000,
        "cubic meters": 0.001,
        "cubic centimeters": 1000,
        "gallons": 0.264172,
        "quarts": 1.05669,
        "pints": 2.11338,
        "cups": 4.16667
    }
    
    if from_unit not in volume_units or to_unit not in volume_units:
        return None
    return value * (volume_units[to_unit] / volume_units[from_unit])

def main():
    conversion_types = {
        "length": length_conversion,
        "weight": weight_conversion,
        "volume": volume_conversion
    }

    print("Unit Converter")
    print("Choose conversion type: length, weight, volume")
    conversion_type = input("Enter conversion type: ").strip().lower()

    if conversion_type not in conversion_types:
        print("Invalid conversion type. Please choose from length, weight, or volume.")
        return

    try:
        value = float(input("Enter the value to convert: "))
        from_unit = input("Enter the unit you are converting from: ").strip().lower()
        to_unit = input("Enter the unit you are converting to: ").strip().lower()
        
        conversion_function = conversion_types[conversion_type]
        result = conversion_function(value, from_unit, to_unit)
        
        if result is None:
            print("Invalid units. Please enter correct units for conversion.")
        else:
            print(f"{value} {from_unit} is equal to {result:.4f} {to_unit}")
    
    except ValueError:
        print("Invalid input. Please enter a numeric value.")

if __name__ == "__main__":
    main()


Unit Converter
Choose conversion type: length, weight, volume


Enter conversion type:  length
Enter the value to convert:  200
Enter the unit you are converting from:  meters
Enter the unit you are converting to:  feet


200.0 meters is equal to 656.1680 feet


In [4]:
def perform_operation(numbers, operation):
    try:
        # Check if the list is empty
        if not numbers:
            raise ValueError("The list cannot be empty.")
        
        if operation == 'sum':
            return sum(numbers)
        elif operation == 'average':
            return sum(numbers) / len(numbers)
        elif operation == 'maximum':
            return max(numbers)
        elif operation == 'minimum':
            return min(numbers)
        else:
            raise ValueError("Invalid operation selected.")
    except ValueError as e:
        return f"Error: {e}"

def main():
    print("Welcome to the Mathematical Operations Program!")
    print("Choose an operation:")
    print("1. sum")
    print("2. average")
    print("3. maximum")
    print("4. minimum")
    
    # Get user operation choice
    operation_choice = input("Enter the operation you want to perform (sum, average, maximum, minimum): ").strip().lower()

    # Get the list of numbers
    try:
        numbers_input = input("Enter a list of numbers separated by spaces: ").strip()
        
        # Convert input into a list of numbers
        if numbers_input == "":
            raise ValueError("You must enter at least one number.")
        
        numbers = [float(num) for num in numbers_input.split()]
        
        # Perform the selected operation
        result = perform_operation(numbers, operation_choice)
        print(f"The result of {operation_choice} is: {result}")
    
    except ValueError as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    main()


Welcome to the Mathematical Operations Program!
Choose an operation:
1. sum
2. average
3. maximum
4. minimum


Enter the operation you want to perform (sum, average, maximum, minimum):  sum
Enter a list of numbers separated by spaces:  2 3 4


The result of sum is: 9.0


In [ ]:
Task-2


In [101]:

def extract_every_other(lst):
    return lst[::2]
input_list = [1, 2, 3, 4, 5, 6]
output = extract_every_other(input_list)
print(output)

[1, 3, 5]


In [104]:

def get_sublist(lst, start, end):
    return lst[start :end+1]
    
input_list = [1, 2, 3, 4, 5, 6]
result = get_sublist(input_list, 2,4)
print(result) 

[3, 4, 5]


In [58]:
def reverse_list(lst):
    return lst[::-1]  # Slicing with -1 to reverse the list


input_list = [ 1,2, 3, 4, 5]
result = reverse_list(input_list)
print(result)  


[5, 4, 3, 2, 1]


In [62]:
def remove_first_last(lst):
    return lst[1:-1]  # Slicing to exclude the first and last elements


input_list = [1, 2, 3, 4, 5]
result = remove_first_last(input_list)
print(result)  


[2, 3, 4]


In [87]:

def get_first_n(lst, n):
    return lst[:n]
input = [1,2,3,4,5]
output = get_first_n (input, n=3)
print(output)




[1, 2, 3]


In [97]:
def get_last_n(lst, n):
    return lst[-n:]

input_list = [1, 2, 3, 4, 5]
output = get_last_n(input_list, 2)
print(output)



[4, 5]


In [99]:

def reverse_skip(lst):
    return lst[-2::-2]

input_list = [1, 2, 3, 4, 5, 6]
output = reverse_skip(input_list)
print(output)


[5, 3, 1]


In [ ]:
4.3 Exercise on Nested List:

In [6]:
def flatten(lst):
    flattened = []
    for item in lst:
        if isinstance(item, list):
            flattened.extend(flatten(item))  # Recursively flatten the nested list
        else:
            flattened.append(item)  # Add the element to the flattened list
    return flattened

nested_list = [[1, 2], [3, 4], [5]]
flattened_list = flatten(nested_list)
print(flattened_list)  


[1, 2, 3, 4, 5]


In [7]:
def access_nested_element(lst, indices):
    for index in indices:
        lst = lst[index]  # Access the element at the current index
    return lst

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
element = access_nested_element(nested_list, indices)
print(element) 


6


In [8]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)  # Recursively sum the elements of the nested list
        else:
            total += item  # Add the number to the total sum
    return total

nested_list = [[1, 2], [3, [4, 5]], 6]
total_sum = sum_nested(nested_list)
print(total_sum)  


21


In [11]:
def remove_element(lst, elem):
    for i in range(len(lst)):
        if isinstance(lst[i], list):  # If the element is a sublist, recursively call remove_element
            lst[i] = remove_element(lst[i], elem)
        else:
            if lst[i] == elem:  # Remove the element if it matches
                lst[i] = None  # Mark the element for removal by setting it to None
    # Remove any `None` values and empty sublists
    return [sublist for sublist in lst if sublist != [] and sublist != None]

nested_list = [[1, 2], [3, 2], [4, 5]]
element_to_remove = 2
modified_list = remove_element(nested_list, element_to_remove)
print(modified_list) 




[[1], [3], [4, 5]]


In [12]:
def find_max(lst):
    max_value = float('-inf')  # Initialize with the smallest possible value
    for item in lst:
        if isinstance(item, list):
            max_value = max(max_value, find_max(item))  # Recursively find max in the nested list
        else:
            max_value = max(max_value, item)  # Update max_value if a larger element is found
    return max_value

nested_list = [[1, 2], [3, [4, 5]], 6]
max_element = find_max(nested_list)
print(max_element)  


6


In [13]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):  # If the element is a sublist, recursively call count_occurrences
            count += count_occurrences(item, elem)
        else:
            if item == elem:  # If the element matches, increment the count
                count += 1
    return count


nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
occurrences = count_occurrences(nested_list, element_to_count)
print(occurrences)  


3


In [14]:
def deep_flatten(lst):
    flattened = []
    for item in lst:
        if isinstance(item, list):  # If the item is a list, recursively flatten it
            flattened.extend(deep_flatten(item))
        else:
            flattened.append(item)  # If the item is not a list, add it directly
    return flattened


nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
flattened_list = deep_flatten(nested_list)
print(flattened_list)  


[1, 2, 3, 4, 5, 6, 7, 8]


In [16]:
def average_nested(lst):
    total = 0
    count = 0
    
    # Flatten the nested list and sum all elements
    for item in lst:
        if isinstance(item, list):  # If the item is a sublist, recursively call average_nested
            sub_total, sub_count = average_nested(item)  # Fix here, calling average_nested to get the sum and count
            total += sub_total
            count += sub_count
        else:
            total += item  # Add the item to the total sum
            count += 1  # Increment the count for each element
    
    # Return both total sum and count for calculating average later
    return total, count

def calculate_average(lst):
    total, count = average_nested(lst)
    return total / count if count != 0 else 0


nested_list = [[1, 2], [3, 4], [5, 6]]
average = calculate_average(nested_list)
print(average)



3.5


In [ ]:
 NumPy

In [17]:
array_2x2 = [[None, None], [None, None]]
array_2x2_zeros = [[0, 0], [0, 0]]

print(array_2x2)         
print(array_2x2_zeros)   


[[None, None], [None, None]]
[[0, 0], [0, 0]]


In [18]:
# Initialize a 4x2 array with all ones using list comprehension
array_4x2_ones = [[1 for _ in range(2)] for _ in range(4)]

print(array_4x2_ones)  


[[1, 1], [1, 1], [1, 1], [1, 1]]


In [20]:
import numpy as np

# Create a 4x2 array filled with 7, with integer type
array_4x2 = np.full((4, 2), 7, dtype=int)

# Create a 3x3 array filled with 3.14, with float type
array_3x3 = np.full((3, 3), 3.14, dtype=float)

print(array_4x2)


print(array_3x3)



[[7 7]
 [7 7]
 [7 7]
 [7 7]]
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]


In [21]:
import numpy as np

# Create a sample array
original_array = np.array([[1, 2], [3, 4]])

# Create a new array of zeros with the same shape and type as original_array
zeros_array = np.zeros_like(original_array)

print(zeros_array)



[[0 0]
 [0 0]]


In [22]:
import numpy as np

# Create a sample array
original_array = np.array([[1, 2], [3, 4]])

# Create a new array of ones with the same shape and type as original_array
ones_array = np.ones_like(original_array)

print(ones_array)



[[1 1]
 [1 1]]


In [23]:
import numpy as np

# Existing list
new_list = [1, 2, 3, 4]

# Convert the list to a NumPy array
numpy_array = np.array(new_list)

print(numpy_array)



[1 2 3 4]


In [ ]:
Problem - 2

In [24]:
import numpy as np

# Create an array with values ranging from 10 to 49
array = np.arange(10, 50)

print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [25]:
import numpy as np

# Create an array with values ranging from 0 to 8
array = np.arange(9)

# Reshape the array into a 3x3 matrix
matrix = array.reshape(3, 3)

print(matrix)



[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
import numpy as np

# Create a 3x3 identity matrix
identity_matrix = np.eye(3)

print(identity_matrix)



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
import numpy as np

# Create a random array of size 30 with values between 0 and 1
random_array = np.random.random(30)

# Find the mean of the array
mean_value = random_array.mean()

print("Random Array:", random_array)
print("Mean of the array:", mean_value)


Random Array: [0.33559958 0.69514494 0.56022175 0.82238458 0.4915018  0.0113762
 0.87937547 0.09014472 0.2398041  0.36293199 0.95617056 0.95560736
 0.90335159 0.92604243 0.44984543 0.11032763 0.53931955 0.91147831
 0.09661114 0.73140742 0.69857332 0.1668655  0.77561159 0.99865362
 0.13195672 0.63744073 0.52469547 0.13639195 0.52108207 0.59434831]
Mean of the array: 0.5418088607546806


In [28]:
import numpy as np

# Create a 10x10 array with random values between 0 and 1
random_array_10x10 = np.random.random((10, 10))

# Find the minimum and maximum values in the array
min_value = random_array_10x10.min()
max_value = random_array_10x10.max()

print("Random 10x10 Array:")
print(random_array_10x10)

print("Minimum value:", min_value)
print("Maximum value:", max_value)


Random 10x10 Array:
[[0.97849634 0.16957003 0.69749651 0.43934516 0.09350802 0.16805609
  0.96898382 0.85004673 0.80418736 0.9735456 ]
 [0.95650666 0.23635539 0.46900482 0.3677992  0.1004135  0.0149707
  0.39767488 0.71365404 0.32154518 0.85424078]
 [0.07841038 0.14644162 0.55671206 0.10873663 0.81387275 0.97287864
  0.87190956 0.46515838 0.20036436 0.03026802]
 [0.91498365 0.90147144 0.39533149 0.88997346 0.24555157 0.03930755
  0.6647139  0.55775232 0.1946223  0.77608159]
 [0.11843391 0.62408212 0.56228761 0.39607387 0.32588894 0.54458075
  0.57813001 0.18669995 0.08753797 0.8329205 ]
 [0.64901492 0.38695983 0.59363276 0.58735892 0.51843579 0.79630535
  0.30852223 0.19616535 0.95098812 0.65613385]
 [0.84368026 0.56301069 0.06030171 0.7547236  0.62810201 0.89678561
  0.12631581 0.95668358 0.66340632 0.11723274]
 [0.75771838 0.3804865  0.78190025 0.64667041 0.74114485 0.62758859
  0.10474236 0.84146054 0.04335257 0.83989865]
 [0.29684986 0.84351097 0.24504282 0.04678758 0.71022367 0.31

In [29]:
import numpy as np

# Create a zero array of size 10
zero_array = np.zeros(10)

# Replace the 5th element (index 4) with 1
zero_array[4] = 1

print(zero_array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [30]:
import numpy as np

arr = [1, 2, 0, 0, 4, 0]

# Reverse the array using np.flip
reversed_arr = np.flip(arr)

print(reversed_arr)



[0 4 0 0 2 1]


In [31]:
import numpy as np

# Define the size of the 2D array (e.g., 5x5)
size = 5

# Create a 2D array with all elements initialized to 0
array = np.zeros((size, size), dtype=int)

# Set the border elements to 1
array[0, :] = 1  # Top row
array[-1, :] = 1  # Bottom row
array[:, 0] = 1  # Left column
array[:, -1] = 1  # Right column

print(array)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [32]:
import numpy as np

# Create an 8x8 matrix
size = 8
checkerboard = np.zeros((size, size), dtype=int)

# Fill the checkerboard pattern (alternating 1s and 0s)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [33]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Add the two arrays
result_addition = np.add(x, y)

print(result_addition)


[[ 6  8]
 [10 13]]


In [34]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Subtract the two arrays
result_subtraction = np.subtract(x, y)

print(result_subtraction)


[[-4 -4]
 [-4 -3]]


In [35]:
import numpy as np

# Given array
x = np.array([[1, 2], [3, 5]])

# Multiply the array by an integer (e.g., 3)
result_multiplication = x * 3

print(result_multiplication)


[[ 3  6]
 [ 9 15]]


In [36]:
import numpy as np

# Given array
x = np.array([[1, 2], [3, 5]])

# Square each element of the array
result_square = np.power(x, 2)

print(result_square)


[[ 1  4]
 [ 9 25]]


In [37]:
import numpy as np

# Given arrays
v = np.array([9, 10])
w = np.array([11, 12])
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

# Dot product between v and w
dot_vw = np.dot(v, w)
print(f"Dot product of v and w: {dot_vw}")

# Dot product between x and v
dot_xv = np.dot(x, v)
print(f"Dot product of x and v: {dot_xv}")

# Dot product between x and y
dot_xy = np.dot(x, y)
print(f"Dot product of x and y: \n{dot_xy}")


Dot product of v and w: 219
Dot product of x and v: [29 77]
Dot product of x and y: 
[[19 22]
 [50 58]]


In [38]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Concatenate x and y along rows (horizontally)
concat_xy_rows = np.concatenate((x, y), axis=1)
print(f"Concatenated x and y along rows: \n{concat_xy_rows}")

# 2. Concatenate v and w along columns (vertically)
# First, reshape v and w to make them 2D arrays (for vertical stacking)
v_reshaped = v.reshape(-1, 1)
w_reshaped = w.reshape(-1, 1)

concat_vw_cols = np.vstack((v_reshaped, w_reshaped))
print(f"Concatenated v and w along columns: \n{concat_vw_cols}")


Concatenated x and y along rows: 
[[1 2 5 6]
 [3 5 7 8]]
Concatenated v and w along columns: 
[[ 9]
 [10]
 [11]
 [12]]


In [40]:
import numpy as np

# Given arrays
x = np.array([[1, 2], [3, 5]])  # 2x2 matrix
v = np.array([9, 10])            # 1D array

# Reshape v to make it a 2D array with shape (2, 1)
v_reshaped = v.reshape(-1, 1)

# Now concatenate x and v_reshaped along rows (axis=1)
concat_xv = np.concatenate((x, v_reshaped), axis=1)

print(concat_xv)



[[ 1  2  9]
 [ 3  5 10]]
